name: Download and push a folder

on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  download-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download folder
        run: wget -r -N -l inf ftp://117.254.209.21/B.%20E/FIRST%20YEAR/ -O /tmp/download
        
      - name: Push to repository
        uses: actions/upload-artifact@v3
        with:
          artifact: '/tmp/download/117.254.209.21/B. E'
          repository: rcoem_papers/main
